# Generated by Django 2.1.4 on 2018-12-25 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightnovel',
            name='ngayup',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày upload'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chuong',
            name='ngayup',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày upload'),
            preserve_default=False,
        ),
    ]
