# Generated by Django 2.1.4 on 2018-12-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0002_auto_20181225_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuong',
            name='ngayup',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='ngayup',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload'),
        ),
    ]
