# Generated by Django 2.1.4 on 2018-12-25 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0003_auto_20181225_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuong',
            name='ngayup',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày upload'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='ngayup',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Ngày upload'),
        ),
    ]
