# Generated by Django 2.1.4 on 2018-12-25 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0004_auto_20181225_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chuong',
            name='ngayup',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày upload'),
        ),
        migrations.AlterField(
            model_name='lightnovel',
            name='ngayup',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày upload'),
        ),
    ]
