# Generated by Django 2.1.4 on 2018-12-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightnovel', '0007_auto_20181225_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightnovel',
            name='dahoanthanh',
            field=models.BooleanField(default=False, verbose_name='Check vào nếu bộ truyện này đã hoàn thành'),
        ),
    ]
