# Generated by Django 2.1.4 on 2018-12-26 13:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lightnovel', '0010_auto_20181226_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightnovel',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
