# Generated by Django 2.1.4 on 2018-12-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentruyen', models.CharField(max_length=100, verbose_name='Tên truyện')),
                ('tacgia', models.CharField(max_length=100, verbose_name='Tác giả')),
                ('anh', models.ImageField(upload_to='AudioThumbnail', verbose_name='Ảnh')),
                ('gioithieu', models.TextField(blank=True, default='', null=True, verbose_name='Giới thiệu')),
            ],
            options={
                'verbose_name': 'Danh sách các truyện Audio',
                'verbose_name_plural': 'Danh sách các truyện Audio',
            },
        ),
        migrations.CreateModel(
            name='Tap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tap', models.CharField(max_length=10, verbose_name='Tập')),
                ('tentap', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Tiêu đề tập')),
                ('fileaudio', models.FileField(upload_to='AudioFile', verbose_name='File audio')),
                ('ngayup', models.DateTimeField(blank=True, null=True, verbose_name='Ngày upload')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audio.Audio')),
            ],
            options={
                'verbose_name': 'Tập từng truyện Audio',
                'verbose_name_plural': 'Tập từng truyện Audio',
            },
        ),
        migrations.CreateModel(
            name='TheLoaiAU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=20, verbose_name='Tên thể loại')),
            ],
            options={
                'verbose_name': 'Danh sách thể loại',
                'verbose_name_plural': 'Danh sách thể loại',
            },
        ),
        migrations.AddField(
            model_name='audio',
            name='theloai',
            field=models.ManyToManyField(blank=True, default='', to='audio.TheLoaiAU'),
        ),
    ]
