# Generated by Django 2.1.4 on 2018-12-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20181225_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='dahoanthanh',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tap',
            name='audio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='audio.Audio'),
        ),
    ]
