# Generated by Django 2.1.4 on 2018-12-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_auto_20181225_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'verbose_name': 'Quản lý danh sách các truyện NGHE', 'verbose_name_plural': 'Quản lý danh sách các truyện NGHE'},
        ),
        migrations.AlterModelOptions(
            name='tap',
            options={'verbose_name': 'Quản lý danh sách các tập truyện NGHE', 'verbose_name_plural': 'Quản lý danh sách các tập truyện NGHE'},
        ),
        migrations.AlterModelOptions(
            name='theloaiau',
            options={'verbose_name': 'Quản lý danh sách thể loại', 'verbose_name_plural': 'Quản lý danh sách thể loại'},
        ),
    ]
